### ISSUE TITLE
Alert on No Audio

### ISSUE THREAD

**Issue by DavidRueter** [directmusic/MiniMetersServer#2]
Feature Request : Add a feature to generate an alert when there is no audio on a particular input.

It would be great if this could be configurable... such as to send an alert when this condition is encountered, threshold for detecting the condition, when / how monitoring for this condition should begin.

Use case:  Live events that are recorded in a DAW or live streamed can encounter a missing audio problem that goes unnoticed for lots of different reasons.  Alerting the operator would be a wonderful safeguard.

**Comment by directmusic** [comment]
This is an issue for MiniMeters, not the server plugin. Please leave feature requests in the Discord.
