### ISSUE TITLE
MiniMetersServer Integration Failure

### ISSUE THREAD

**Issue by acook** [directmusic/MiniMetersServer#5]
The plugin side loads fine as both Clap and VST3, but when I switch to the plugin audio source in the app, the meter freezes. Other audio sources from my various sound devices work fine.

I don't know if it is just IPC failure, since the app's meters freeze and stop updating entirely - whatever waveform is visible from another sound source stays. The app itself continues to work, so I can switch away to another sound device and the meters will start updating again.

- Bitwig 5.2b10
- Solus Linux (Budgie, X11, PipeWire)

**Comment by directmusic** [comment]
Hey! Thank you for your patience on this issue. Some users have reported issues similar to this but it's always been a misunderstanding, however this seems quite like a legitimate IPC issue so I am intrigued. 

As long as MiniMetersServer says it is the primary instance in the GUI it should be able to communicate with MiniMeters without issue.

At the moment, the meters pause if no new audio is available which tracks with your issue. Bitwig _does_ do sandboxing as I am sure you're aware but I haven't received reports of that being an issue and in my macOS testing that doesn't prevent a memory mapped file from working correctly. I will not be able to install Solus to test for another couple days, but am happy to do so after the weekend. Do you have any other specific settings or info you can give me to help replicate?

Thanks

**Comment by acook** [comment]
Thank you for your initiative. I've done some additional testing.

It does say that it is the primary instance.

But it looks like the issue is with the new version of Bitwig.

- I just tested with v5.1.9 stable and it works without issues. 
- I updated my 5.2b10 beta to v5.2 stable (just released today) and it does not work either.

It also could be an issue with Flatpak's sandbox, since Bitwig has started distributing as Flatpaks. That is the other major difference between my v5.1.9 install (non-Flatpak) and v5.2. 

I'm going to extract the `.deb` version and see if it has the same problem as the `.flatpak`.

**Comment by acook** [comment]
Okay I thought that was going to take longer to do, but it was pretty simple to just run it it from the extracted archive.

The issue is *not* present in the non-Flatpak version. 

So this is likely a Flatpak sandbox issue. I'm not well versed in the way that Flatpak sandboxing works but I see a lot of complaints about it.

**Comment by directmusic** [comment]
Thank you for the investigative work! I will add a note to the Known Issues page on the website and see if I can figure out a solution.
